# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'watchbus' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for watchbus
  pod 'RNMobileCenter', '~> 0.3.0'
  pod 'MobileCenter', '~> 0.5.0'

  

  target 'watchbusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'watchbus-tvOS' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for watchbus-tvOS

  target 'watchbus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
